- name: Ddeploy webapp
  become: false
  synchronize:
    src: "{{ playbook_dir }}/../webapp/php/"
    dest: "/home/{{ isucon_user }}/webapp/php/"
    recursive: true
    use_ssh_args: true
    delete: false

- name: Deploy sql
  become: false
  synchronize:
    src: "{{ playbook_dir }}/../webapp/sql/"
    dest: "/home/{{ isucon_user }}/webapp/sql/"
    recursive: true
    use_ssh_args: true
    delete: false

#- name: Composer install
#  become: false
#  command:
#    cmd: /usr/local/bin/composer install --no-dev --optimize-autoloader
#    chdir: "/home/{{ isucon_user }}/webapp/php"

- name: Deploy env.sh
  become: false
  copy:
    src: "{{ playbook_dir }}/../env.sh"
    dest: "/home/{{ isucon_user }}/env.sh"
    mode: 0644
  notify: restart webapp
